### ISSUE TITLE
Gracefully handle overlong credential IDs

### ISSUE THREAD

**Issue by robin-nitrokey** [solokeys/fido-authenticator#15]
The Google CTAP2 test suite currently causes a panic in [credential.rs:255](https://github.com/solokeys/fido-authenticator/blob/0.1.0/src/credential.rs#L255).  From my understanding, this is due to the encrypted credential ID being longer than `MAX_CREDENTIAL_ID_LENGTH` (255).  We should at least return an error instead of panicking.

<details>

```
#0  panic_halt::panic (_info=<optimized out>) at /home/sz/.cargo/registry/src/github.com-1ecc6299db9ec823/panic-halt-0.2.0/src/lib.rs:32
#1  0x0001ba20 in core::panicking::panic_fmt () at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a//library/core/src/panicking.rs:116
#2  0x0001c050 in core::result::unwrap_failed () at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a//library/core/src/result.rs:1690
#3  0x000113d8 in core::result::Result<fido_authenticator::credential::CredentialId, ctap_types::ctap2::Error>::unwrap<fido_authenticator::credential::CredentialId, ctap_types::ctap2::Error> (self=...) at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1018
#4  fido_authenticator::credential::Credential::id<trussed::client::ClientImplementation<runner::types::Syscall>> (self=<optimized out>, trussed=<optimized out>, key_encryption_key=..., rp_id_hash=...) at /home/sz/.cargo/registry/src/github.com-1ecc6299db9ec823/fido-authenticator-0.1.0/src/credential.rs:255
#5  0x000067e6 in fido_authenticator::ctap2::{impl#0}::make_credential<fido_authenticator::Conforming, trussed::client::ClientImplementation<runner::types::Syscall>> (self=0x2003c800 <runner::APP::apps>, parameters=<optimized out>) at /home/sz/.cargo/registry/src/github.com-1ecc6299db9ec823/fido-authenticator-0.1.0/src/ctap2.rs:368
#6  0x0000dd74 in ctap_types::ctap2::Authenticator::call_ctap2<fido_authenticator::Authenticator<fido_authenticator::Conforming, trussed::client::ClientImplementation<runner::types::Syscall>>> (self=0x2b <__EXCEPTIONS+35>, request=<optimized out>) at /home/sz/.cargo/registry/src/github.com-1ecc6299db9ec823/ctap-types-0.1.2/src/ctap2.rs:458
#7  0x0000fc70 in fido_authenticator::dispatch::try_get_ctap2_response<trussed::client::ClientImplementation<runner::types::Syscall>, fido_authenticator::Conforming> (authenticator=0x2003c800 <runner::APP::apps>, data=...) at /home/sz/.cargo/registry/src/github.com-1ecc6299db9ec823/fido-authenticator-0.1.0/src/dispatch.rs:173
#8  0x0000fb7a in fido_authenticator::dispatch::try_handle_ctap2<trussed::client::ClientImplementation<runner::types::Syscall>, fido_authenticator::Conforming> (authenticator=<optimized out>, data=..., response=<optimized out>) at /home/sz/.cargo/registry/src/github.com-1ecc6299db9ec823/fido-authenticator-0.1.0/src/dispatch.rs:144
#9  0x0000fa4a in fido_authenticator::dispatch::handle_ctap2<trussed::client::ClientImplementation<runner::types::Syscall>, fido_authenticator::Conforming> (authenticator=0x3efde <.Lanon.b7f9711851ba8db6fe8fed9a6c5d3f8f.81>, data=..., response=0x200341c4 <ctaphid_dispatch::types::HidInterchange::split::INTERCHANGES+8>) at /home/sz/.cargo/registry/src/github.com-1ecc6299db9ec823/fido-authenticator-0.1.0/src/dispatch.rs:69
#10 0x0000f570 in fido_authenticator::dispatch::ctaphid::{impl#0}::call<fido_authenticator::Conforming, trussed::client::ClientImplementation<runner::types::Syscall>> (self=0x3efde <.Lanon.b7f9711851ba8db6fe8fed9a6c5d3f8f.81>, command=..., request=0x20030b60, response=0x3c500) at /home/sz/.cargo/registry/src/github.com-1ecc6299db9ec823/fido-authenticator-0.1.0/src/dispatch/ctaphid.rs:36
#11 0x00021c02 in ctaphid_dispatch::dispatch::Dispatch::call_app (self=0x2003c7f8 <runner::APP::ctaphid_dispatch>, app=..., command=..., request=0x20030b60) at /home/sz/.cargo/registry/src/github.com-1ecc6299db9ec823/ctaphid-dispatch-0.1.0/src/dispatch.rs:50
#12 0x00021b6c in ctaphid_dispatch::dispatch::Dispatch::poll (self=0x2003c7f8 <runner::APP::ctaphid_dispatch>, apps=...) at /home/sz/.cargo/registry/src/github.com-1ecc6299db9ec823/ctaphid-dispatch-0.1.0/src/dispatch.rs:67
#13 0x000025ba in runner::idle::{closure#2} (apps=...) at src/main.rs:166
#14 runner::types::Apps::ctaphid_dispatch<runner::idle::{closure#2}, bool> (self=<optimized out>, f=...) at src/types.rs:287
#15 0x000015b6 in runner::idle (c=...) at src/main.rs:166
#16 0x0000feac in runner::APP::main () at src/main.rs:35
(gdb) 

-------------------------
Please touch your security key!                                                                                       
Test successful: Tests if MakeCredential works with parameters of the wrong type.                                     
Expected error code `CTAP2_ERR_CBOR_UNEXPECTED_TYPE`, got `CTAP2_ERR_INVALID_CBOR`.                                   
Test successful: Tests if MakeCredential works with missing parameters.                                               
Failed test: Tests bad parameters in RP entity parameter of MakeCredential. - Optional entry icon not recognized.     
A prompt was expected, but not performed. Sometimes it is just not recognized if performed too fast.                  
The failing error code is `CTAP2_ERR_INVALID_CBOR`.                                                                   
Please touch your security key!                                                                                       
Test successful: Tests bad parameters in user parameter of MakeCredential.                                            
A prompt was expected, but not performed. Sometimes it is just not recognized if performed too fast.     
```
</details>

Original report: https://github.com/Nitrokey/nitrokey-3-firmware/issues/49

**Comment by robin-nitrokey** [comment]
Didn’t mean to close this as it is only fixed in our fork.
